#!/bin/bash
# 02614 - High-Performance Computing, January 2024
# 
# batch script to run matmult on a dedicated GPU server in the hpcintrogpu
# queue
#
# Author: Bernd Dammann <bd@cc.dtu.dk>
#         Hans Henrik Brandenborg Sørensen <hhbs@dtu.dk>
#
#BSUB -J ncu_prof
#BSUB -o ncu_prof_%J.out
#BSUB -q hpcintrogpu
#BSUB -n 32
#BSUB -R "rusage[mem=2048]"
#BSUB -W 15
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"

# define the driver name to use
# valid values: matmult_c.nvc++, matmult_f.nvc++
#
EXECUTABLE=matmult_c.nvc++

# define the mkn values in the MKN variable
#
SIZE="1000"

# define the method type in TYPE
#
TYPE="mnk_offload"

# you have exclusive access to the GPU and only need 1 iteration from
# the driver for ncu to collect metrics with high accuary
#
export MFLOPS_MAX_IT=1
export MATMULT_COMPARE=0

# set tmp dir for profiler lock
#
export TMPDIR=$__LSF_JOB_TMPDIR__

# experiment name 
#
JID=${LSB_JOBID}
EXPOUT="${LSB_JOBNAME}_${JID}"

# load module for shared cuda libraries
module load nvhpc/24.11

# start the collect command with the above settings
ncu -o $EXPOUT \
    --set basic \
    --section MemoryWorkloadAnalysis \
    --section MemoryWorkloadAnalysis_Chart \
    --section ComputeWorkloadAnalysis \
    ./$EXECUTABLE $TYPE $SIZE $SIZE $SIZE

# ncu --config-file off --export /zhome/56/9/140539/nsc_output/report$$.ncu-rep --force-overwrite --section-folder /zhome/56/9/140539/sections --set full --import-source yes --source-folder /zhome/56/9/140539/high_performence_computing/mandotory_assignments/assignment3/02614_Assignment3_matmult/ /zhome/56/9/140539/high_performence_computing/mandotory_assignments/assignment3/02614_Assignment3_matmult/matmult_c.nvc++ mkn_offload 2048 2048 2048

ncu --config-file off --export /zhome/56/9/140539/nsc_output/mnk/mnk_128.ncu-rep --force-overwrite --section-folder /zhome/56/9/140539/sections --set full --import-source yes --source-folder /zhome/56/9/140539/high_performence_computing/mandotory_assignments/assignment3/02614_Assignment3_matmult/ /zhome/56/9/140539/high_performence_computing/mandotory_assignments/assignment3/02614_Assignment3_matmult/matmult_c.nvc++ mnk_offload 2048 2048 2048